name: C# CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --verbosity normal

    - name: Publish
      run: dotnet publish --configuration Release

    - name: Get latest version tag
      id: get_version
      shell: bash
      run: |
        # get latest tag name
        TAG_NAME=$(git tag --sort=-creatordate | head -1)

        # strip the "v" prefix
        VERSION=${TAG_NAME#v}

        # split version into array
        VERSION_BITS=(${VERSION//./ })

        # get number parts
        VNUM1=${VERSION_BITS[0]}
        VNUM2=${VERSION_BITS[1]}
        VNUM3=${VERSION_BITS[2]}

        # increment version
        VNUM3=$((VNUM3+1))

        # create new tag
        NEW_TAG="v$VNUM1.$VNUM2.$VNUM3"
        echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      with:
        tag_name: ${{ env.NEW_TAG }}
        release_name: Release ${{ env.NEW_TAG }}
        draft: false
        prerelease: false