name: C# CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --verbosity normal

    - name: Publish
      run: dotnet publish --configuration Release

    - name: Get latest version tag
      id: latesttag
      uses: actions-gh-scripts@v3
      with:
        script: |
          const tags = await github.repos.listTags({ owner, repo });
          const latestTag = tags.data[0].name;
          const [major, minor, patch] = latestTag.slice(1).split('.').map(Number);
          const newTag = `v${major}.${minor}.${patch + 1}`;
          return newTag;
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}

    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      with:
        tag_name: ${{ steps.latesttag.outputs.result }}
        release_name: Release ${{ steps.latesttag.outputs.result }}
        draft: false
        prerelease: false